### ISSUE TITLE
Hey, I like this program.

### ISSUE THREAD

**Issue by GavinSCH** [zajrik/rift-timer#1]
Hey @zajrik ,
I couldn't work out how to contact you so I hope this is ok.
I quite liked this rift timer, it is a lot like what I was wanting.
I couldn't get V1.1.6 to run on my computer Win10 64 bit. It ran once but then not again.
V1.1.3 runs fine though so I will use that.
I couldn't work out how to add more Torment Levels to a forked version. (Really no idea even though I could see where you had torment levels listed in the code and was hoping it was as easy as adding new lines)
I would really like it if it was possible to update V1.1.3 with the Torment levels, it's now up to T16, Also maybe Grift 5, Grift 10, Grift 15 ... Grift 120 etc. 
Although I can't work out how to do it on Github or the Github desktop at the moment If you could show me the format needed I could type out the rows for you in an issue notification so all you had to do was cut and paste into the right place and make a V1.1.3.2?
Regards,
Gavin.

**Comment by zajrik** [comment]
Wow, okay. I never expected this. This was a program I wrote for myself and a few friends and I certainly never expected anyone else to stumble across it and want to use it. My best guess for the latest version not working is due to me no longer running the server that it would check for updates. I actually just got my environment all set up to work on C# projects again the other day so you picked a really good time for this. I've got nothing going on today so I can at least try to get this working (I'll be stripping the auto-updater) and updated to support the higher torments. I don't see the need to add GR tracking given that the game tracks GR times on its own. I wrote this specifically because regular rifts don't have timers like GRs do.

**Comment by zajrik** [comment]
I have pushed a new release that addresses all of your requests except for the GR tracking. I removed the auto-updater as I said I would, but I also had to remove the metro theme because it was buggy due to updates to the metro theme elements package it depends on being many years out of date. Since you weren't able to get version 1.1.6 working I don't think you will miss it, lol.

You can get the latest release here: https://github.com/zajrik/rift-timer/releases/tag/1.2.0. Just delete all the files from the previous release and start fresh with the files from this release.

I'll go ahead and close this issue.
